### PR TITLE
Fix/30 previous search results

### LINKED ISSUE #30: Previous Search Results
Internship search should display a list of previous internship search results (up to 12)

Screenshot 2021-05-11 at 02 27 41

### PR DESCRIPTION
**Pull request by LiFaytheGoblin**
now, previousely queried internships are displayed with the search results

also refactors the search view to have search result list components, which in turn have search result components

fixes #30 

fixes #247

I changed the logic of the get internship controller a little: It now only gets seen or not-seen internships (depending on the query parameter "seen"), it doesn't add those seen to those unseen. This new logic corresponds to what the front end expects.

### CODE REVIEW

File: client/src/components/search/SearchResult.vue [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+    operationalArea: String,
+    programmingLanguages: [String],
+  },
+  data() {
+    return {
+    };
+  },
+  methods: {
+
+  },
```
Comment (Kaes3kuch3n) [inline client/src/components/search/SearchResult.vue]:
```suggestion
```
Kann eigentlich weg, oder?

File: client/src/components/search/SearchResultList.vue [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+    resultCountText: String,
+    searchResults: [],
+  },
+  data() {
+    return {
+    };
+  },
+  methods: {
+
+  },
```
Comment (Kaes3kuch3n) [inline client/src/components/search/SearchResultList.vue]:
```suggestion
```

**Review by Kaes3kuch3n — CHANGES_REQUESTED** [review]
